### ISSUE TITLE
Add support for powerbi report server

### ISSUE THREAD

**Issue by shohamyamin** [pichlerpa/PowerBITrinoConnector#12]
How we can add support for this connector in Powerbi report server?

**Comment by pichlerpa** [comment]
Hey @shohamyamin, 

custom connectors are not supported with Power BI Report Server also the number of connectors is generally limited: https://learn.microsoft.com/en-us/power-bi/report-server/data-sources

However, you could try to re-build some of the logic yourself. This connector is also just using the web connector (Web.Contents) talking to the Trino REST API under the hood.

Patrick

**Comment by shohamyamin** [comment]
What you mean in "re-build some of the logic". you mean somehow to use WEB Datasource in the power-bi report server?

I am interested in connecting the PowerBI report server to Trino but I don't see how this can be achieved and if so maybe to make it somehow to even delegate the user to Trino(maybe with user impersonation)

**Comment by pichlerpa** [comment]
Exactly, you could take [this](https://github.com/pichlerpa/PowerBITrinoConnector/blob/master/Trino/Trino.pq#L80C1-L109C27) code part as a starter. I will close this issue as it's not directly related to the connector.
