### ISSUE TITLE
Unable to Refresh from Gateway server

### ISSUE THREAD

**Issue by jlriverayuso** [pichlerpa/PowerBITrinoConnector#13]
<html>
<body>
<p style="box-sizing: border-box; margin: 0px; color: rgb(0, 0, 0); font-family: SegoeUI, Lato, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">although the data refreshes fine form othe Personal Mode Data Gateway, when published to the Power BI Service i just get the following error: </p>
{"error":{"code":"DM_GWPipeline_Gateway_InvalidMashupConnectionString","pbi.error":{"code":"DM_GWPipeline_Gateway_InvalidMashupConnectionString","parameters":{},"details":[],"exceptionCulprit":1}}} Table:
--
Cluster URI: | usgovcloudapi.net

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by pichlerpa** [comment]
Hey @jlriverayuso,

have you made sure to enable "Allow user’s custom data connectors to refresh through this gateway cluster" when setting up the gateway in the Power BI Service and did the connection test work when configuring the data source? 

Regards,
Patrick

**Comment by jlriverayuso** [comment]
Hi! @pichlerpa ,
 yes, this option has been enabled. that error comes up when it tries to refresh the data.
 
![image](https://github.com/pichlerpa/PowerBITrinoConnector/assets/48562308/2fcfe4fd-82e8-4f04-a277-028235ffd93e)

**Comment by pichlerpa** [comment]
Hi @jlriverayuso,

That's difficult to troubleshoot, but you could download some sort of HTTP sniffer such as [Fiddler](https://www.telerik.com/download/fiddler) for checking what HTTP requests are being sent and what's going on behind the scenes. It worked on my end before uploading the .MEZ file using a non-personal gateway.

Regards,
Patrick

**Comment by pichlerpa** [comment]
Hey @jlriverayuso,

It seems to like the Power BI service finally can't access the custom connector, maybe somehow related to the first point here:
https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors#considerations-and-limitations

Patrick
