### ISSUE TITLE
Can't add custom connector

### ISSUE THREAD

**Issue by Khoi1201** [pichlerpa/PowerBITrinoConnector#2]
Hi, I'm trying to add custom connector but it not show up in "Get Data" window.
I follow the instruction and create custom connector
![image](https://user-images.githubusercontent.com/90588753/190229159-22cbb7d0-1a93-4d0b-88e4-a0c25a7fd178.png)
and put the file there
![image](https://user-images.githubusercontent.com/90588753/190229224-57e55902-892a-4be0-b8c1-3d0d9a1d831b.png)
I change the option as the instruction
![image](https://user-images.githubusercontent.com/90588753/190229709-82ffb594-9133-49fb-b311-af31b8ffa53c.png)
but it just won't work
![image](https://user-images.githubusercontent.com/90588753/190229403-35528b1d-d080-459f-a766-7e9a999e9855.png)
Thank you for your time.

**Comment by pichlerpa** [comment]
Hi @Khoi1201, check again your directory where you put the connector, it seems to be wrong. It should be: [Documents]\Power BI Desktop\Custom Connectors. 

Patrick

**Comment by Khoi1201** [comment]
Thanks you, I have found the right folder for it.

**Comment by Khoi1201** [comment]
Hi @pichlerpa, I came across a new error when trying to connect to Trino,
![image](https://user-images.githubusercontent.com/90588753/190351575-07ba6d6a-4c37-4ab8-9f4f-cca163b6a40e.png)
I keep all the default setting for power BI and Trino and can't connect to Trino, host name is localhost, port is 8080
I leave the rest blank and the error say:
![image](https://user-images.githubusercontent.com/90588753/190351961-70a59d91-e027-4736-a908-3e903693a1fa.png)
I can connect to trino through my browser using the same URL:
![image](https://user-images.githubusercontent.com/90588753/190352357-7cb8ea90-54d3-4b70-9f97-62621fd586ca.png)

**Comment by pichlerpa** [comment]
@Khoi1201 try changing "localhost" to "host.docker.internal", which is [the host IP](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) if you are using Docker Desktop.

**Comment by Khoi1201** [comment]
I tried and it give the same result 
![image](https://user-images.githubusercontent.com/90588753/190410554-7ad39b8d-93ce-4276-b5fd-23a8fc7f9499.png)
![image](https://user-images.githubusercontent.com/90588753/190410646-3cae0268-c4e9-401a-a4bc-59809be4c57e.png)

**Comment by pichlerpa** [comment]
@Khoi1201 check firewall and ports.
