### ISSUE TITLE
Direct Query option to get data from Trino to Power BI

### ISSUE THREAD

**Issue by ha00941527** [pichlerpa/PowerBITrinoConnector#6]
Hey, thanks for sharing this code it helps to connect Trino with Power BI but it does that in import mode only for now. Is it possible that you could help how to add an option for Direct Query?

**Comment by cbource** [comment]
That would be absolutely amazing !

**Comment by pichlerpa** [comment]
Hey, this limitation comes from Power BI, DirectQuery for web sources (Trino REST API) isn't natively supported yet.
