### ISSUE TITLE
Get data based on date filter

### ISSUE THREAD

**Issue by icarocleto** [pichlerpa/PowerBITrinoConnector#8]
First, thanks for the connector, it's working great.

Every time I update the dataset, the connector takes data from the entire database. As my base is growing, this process is getting slower.

I would like to use Power BI's ability to update data incrementally, taking what was added or updated on a specific date range. Is there any way in this connector to configure conditionals to bring filtered records into the query?

**Comment by pichlerpa** [comment]
Hi @icarocleto, yes, it should be technically possible to include this functionality in the connector like in this blog post: https://www.thepoweruser.com/2018/05/08/first-thoughts-on-power-bi-incremental-refresh

Regards,
Patrick
