### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by suishaojian** [pichlerpa/PowerBITrinoConnector#9]
Hi, 
I'm currently facing an issue while configuring the access information for Trino, and it seems like I need to set up SSL certificate authentication. However, I haven't been able to find an option for configuring this in the setup window. How can I resolve this issue? Thank you.

Details: "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

![image](https://github.com/pichlerpa/PowerBITrinoConnector/assets/20984440/2e8dcc32-0700-42af-86ad-e742ad20ce7c)

**Comment by pichlerpa** [comment]
Hi @suishaojian, here you should find everything required to get Trino working under HTTPS: https://trino.io/docs/current/security/tls.html

**Comment by suishaojian** [comment]
> Hi @suishaojian, here you should find everything required to get Trino working under HTTPS: https://trino.io/docs/current/security/tls.html

Hi @pichlerpa ,I am sorry that I may not have made it clear.  I'm currently accessing my company's Trino instance, and SSL is mandatory and cannot be modified. In this situation, if I wish to use the TrinoConnector, how should I set it up?

**Comment by pichlerpa** [comment]
Hi @suishaojian, seems like Trino doesn't support SSL in general anymore, maybe you should consider upgrading to TLS anyway.
https://trino.io/docs/current/security/tls.html#

**Comment by pichlerpa** [comment]
Closed due to no feedback and inactivity.
